### ISSUE TITLE
Deprecate this module

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-aff-free#7]
The motivating case for this is no longer necessary - `HalogenM` now implements `MonadAff`, so `Affable` need not exist anymore.

**Comment by cryogenian** [comment]
:+1:

**Comment by natefaubion** [comment]
How does one deprecate it, other than by just putting up a `DEPRECATED` notice?

**Comment by garyb** [comment]
That's all I was meaning - so at least if people are updating dependencies and come looking for it they can see that it's unnecessary now.

**Comment by garyb** [comment]
38a954b864ca1c443fdf4b3239de70db72653c4b
